---
- name: Configure Logrotate for Minecraft
  ansible.builtin.template:
    src: minecraft-logrotate.j2
    dest: /etc/logrotate.d/minecraft
    owner: root
    group: root
    mode: "0644"

- name: Configure Logrotate for Minecraft Backup
  ansible.builtin.template:
    src: minecraft-backup-logrotate.j2
    dest: /etc/logrotate.d/minecraft-backup
    owner: root
    group: root
    mode: "0644"
