---
- name: Copy Server Template to Minecraft Source
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ minecraft_server_properties_file }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0644'
  notify: restart_minecraft

- name: Copy permissions
  ansible.builtin.template:
    src: permissions.json.j2
    dest: "{{ minecraft_server_permissions_file }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0644'
  notify: restart_minecraft
